---
version: '3'

services:
  itgz-mbs:
    image: itzg/minecraft-bedrock-server:2025.4.0
    environment:
      CHAT_RESTRICTION: "Disabled"
      ENABLE_LAN_VISIBILITY: "true"
      EULA: "TRUE"
      GROW_TREES: "TRUE"
      SERVER_NAME: "Minecraft Bedrock"
    network_mode: "host"
    ports:
      - "19132:19132"
      - "19132:19132/udp"
      - "19133:19133"
      - "19133:19133/udp"
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - bedrock:/data

volumes:
  bedrock:
  # not { external: true } because we want to create this volume as-needed
  # TODO: can we configure this at Wizard ?
